const grads = [["TrueCoders","AL","2","Carrigans Public House"],
["TrueCoders","AL","2","Crossvale"],
["TrueCoders","AL","2","Daxko"],
["TrueCoders","AL","1","Disability:IN"],
["TrueCoders","AL","3","FIS"],
["TrueCoders","AL","1","Giant Eagle Inc."],
["TrueCoders","AL","3","Healthgrades"],
["TrueCoders","AL","2","L&C Designs"],
["TrueCoders","AL","2","Marshmello & Friends Co."],
["TrueCoders","AL","1","NextSite LLC"],
["TrueCoders","AL","2","RxBenefits Inc."],
["TrueCoders","AL","1","ShadowDragon"],
["TrueCoders","AL","2","Target"],
["TrueCoders","AL","2","VIPKid"],
["University of Arizona Boot Camps","AZ","1","AmpleTech Refresh"],
["University of Arizona Boot Camps","AZ","1","Empereon Constar"],
["University of Arizona Boot Camps","AZ","1","ORIANA solutions LLC"],
["University of Arizona Boot Camps","AZ","1","Plexus Worldwide"],
["University of Arizona Boot Camps","AZ","1","Waddell & Reed"],
["Woz U","AZ","2","Accenture"],
["Woz U","AZ","6","Amazon"],
["Woz U","AZ","3","Apple"],
["Woz U","AZ","3","DoorDash"],
["Woz U","AZ","2","Facebook"],
["Woz U","AZ","6","Infosys"],
["Woz U","AZ","2","Intel Corporation"],
["Woz U","AZ","2","Revature"],
["Woz U","AZ","3","Southern Careers Institute"],
["Woz U","AZ","3","Uber"],
["Woz U","AZ","3","United States Postal Service"],
["Woz U","AZ","4","US Army"],
["Woz U","AZ","3","Verizon"],
["Bloc","CA","2","Airbnb"],
["Bloc","CA","15","Apple"],
["Bloc","CA","3","Capital One"],
["Bloc","CA","3","CareerFoundry"],
["Bloc","CA","13","Google"],
["Bloc","CA","3","HubSpot"],
["Bloc","CA","14","Microsoft"],
["Bloc","CA","2","ServiceNow"],
["Bloc","CA","3","Starbucks"],
["Bloc","CA","10","Thinkful"],
["CodingNomads","CA","1","Abarca Health"],
["CodingNomads","CA","1","Answer Digital"],
["CodingNomads","CA","1","Apogee Integration LLC"],
["CodingNomads","CA","1","BCG Platinion"],
["CodingNomads","CA","1","Bit"],
["CodingNomads","CA","1","Citrix"],
["CodingNomads","CA","1","Experian"],
["CodingNomads","CA","1","Floyd County Productions"],
["CodingNomads","CA","1","Nucamp Coding Bootcamp"],
["CodingNomads","CA","1","Philips"],
["CodingNomads","CA","1","VIKTOR"],
["CodingNomads","CA","1","Webhelp"],
["Dev Bootcamp","CA","4","Airbnb"],
["Dev Bootcamp","CA","14","Amazon"],
["Dev Bootcamp","CA","7","Chime"],
["Dev Bootcamp","CA","15","Datadog"],
["Dev Bootcamp","CA","6","Enova International"],
["Dev Bootcamp","CA","17","Google"],
["Dev Bootcamp","CA","10","Home Chef"],
["Dev Bootcamp","CA","5","Indeed.com"],
["Dev Bootcamp","CA","13","Salesforce"],
["Dev Bootcamp","CA","4","ServiceNow"],
["Dev Bootcamp","CA","7","Stitch Fix"],
["Dev Bootcamp","CA","8","ThoughtWorks"],
["Hack Reactor","CA","45","Amazon"],
["Hack Reactor","CA","26","Apple"],
["Hack Reactor","CA","16","Capital One"],
["Hack Reactor","CA","74","Facebook"],
["Hack Reactor","CA","92","Google"],
["Hack Reactor","CA","44","IBM"],
["Hack Reactor","CA","23","JPMorgan Chase & Co."],
["Hack Reactor","CA","25","LinkedIn"],
["Hack Reactor","CA","21","Microsoft"],
["Hack Reactor","CA","34","Personal Projects"],
["Hack Reactor","CA","20","Uber"],
["Hackbright Academy","CA","10","Apple"],
["Hackbright Academy","CA","6","Bloomberg LP"],
["Hackbright Academy","CA","11","Datadog"],
["Hackbright Academy","CA","5","Dropbox"],
["Hackbright Academy","CA","17","Facebook"],
["Hackbright Academy","CA","5","Fastly"],
["Hackbright Academy","CA","25","Google"],
["Hackbright Academy","CA","5","LinkedIn"],
["Hackbright Academy","CA","6","Lyft"],
["Hackbright Academy","CA","8","PagerDuty"],
["Hackbright Academy","CA","6","Salesforce"],
["Hackbright Academy","CA","9","Slack"],
["Hackbright Academy","CA","27","Target"],
["Hackbright Academy","CA","26","Twilio Inc."],
["Holberton School","CA","8","Altimetrik"],
["Holberton School","CA","5","Apple"],
["Holberton School","CA","5","Avantica"],
["Holberton School","CA","10","COMFAMA"],
["Holberton School","CA","16","Globant"],
["Holberton School","CA","12","Koombea"],
["Holberton School","CA","4","Mercado Libre"],
["Holberton School","CA","8","Rappi"],
["Holberton School","CA","9","Seguros Bolivar S.A"],
["Holberton School","CA","4","Siigo S.A."],
["Holberton School","CA","5","Taos"],
["LearningFuze","CA","3","Applied Medical"],
["LearningFuze","CA","5","BeSmartee®"],
["LearningFuze","CA","3","Blizzard Entertainment"],
["LearningFuze","CA","3","Capital Group"],
["LearningFuze","CA","7","Codazen"],
["LearningFuze","CA","7","Doctor Genius"],
["LearningFuze","CA","5","Member Splash"],
["LearningFuze","CA","3","Novvum"],
["LearningFuze","CA","3","Parcel Pending by Quadient"],
["LearningFuze","CA","3","PriceSpider"],
["LearningFuze","CA","3","VaynerCommerce"],
["LearningFuze","CA","7","Verys"],
["LearningFuze","CA","4","VoiceFoundry"],
["Microverse","CA","2","Avance Venture Lab"],
["Microverse","CA","4","CareerFoundry"],
["Microverse","CA","2","MagmaLabs"],
["Microverse","CA","3","NouKòd"],
["Microverse","CA","3","Peoplebox"],
["Microverse","CA","3","Torre"],
["Microverse","CA","14","Upwork"]];
// ["Orange County Code School","CA","2","Apple"],
// ["Orange County Code School","CA","1","AT&T"],
// ["Orange County Code School","CA","1","Bank of the West"],
// ["Orange County Code School","CA","1","Classic Cabinets and Upholstery"],
// ["Orange County Code School","CA","1","Critical Mass"],
// ["Orange County Code School","CA","1","HCA North Florida Division"],
// ["Orange County Code School","CA","2","Intuit"],
// ["Orange County Code School","CA","1","JohnHart Real Estate"],
// ["Orange County Code School","CA","1","Kaiser Permanente"],
// ["Orange County Code School","CA","1","Kareo"],
// ["Orange County Code School","CA","2","Kingsmen Digital Ventures"],
// ["Orange County Code School","CA","1","Transurban"],
// ["Orange County Code School","CA","1","University of California Irvine Division of Continuing Education"],
// ["Orange County Code School","CA","3","Verys"],
// ["Orange County Code School","CA","3","Vincit"],
// ["Redwood Code Academy","CA","1","Action Property Management"],
// ["Redwood Code Academy","CA","1","AUSAM"],
// ["Redwood Code Academy","CA","1","Empower"],
// ["Redwood Code Academy","CA","2","LandMonk"],
// ["Redwood Code Academy","CA","1","Lifehouse Agency"],
// ["Redwood Code Academy","CA","1","Mortgage Machine Services"],
// ["Redwood Code Academy","CA","2","RedApple Digital Health Inc."],
// ["Redwood Code Academy","CA","1","Revature"],
// ["Redwood Code Academy","CA","1","Sonoma State University"],
// ["Redwood Code Academy","CA","1","Tabula Rasa HealthCare"],
// ["Redwood Code Academy","CA","2","TensorIoT Inc."],
// ["Redwood Code Academy","CA","1","Trilogy Education"],
// ["Redwood Code Academy","CA","1","UFC"],
// ["Redwood Code Academy","CA","2","Zigzy"],
// ["Rithm School","CA","1","Accenture"],
// ["Rithm School","CA","2","Birst"],
// ["Rithm School","CA","2","CleverCounsel LLC"],
// ["Rithm School","CA","2","doc.ai"],
// ["Rithm School","CA","6","Dovenmuehle Mortgage Inc."],
// ["Rithm School","CA","2","Dropbox"],
// ["Rithm School","CA","1","Oracle"],
// ["Rithm School","CA","2","Pinterest"],
// ["Rithm School","CA","1","PlanetScale"],
// ["Rithm School","CA","2","Solvd Inc."],
// ["Rithm School","CA","2","Twilio Inc."],
// ["Rithm School","CA","6","WePay"],
// ["Rithm School","CA","2","Workday"],
// ["Rithm School","CA","2","YearOne (Techstars 2020)"],
// ["Springboard","CA","11","Accenture"],
// ["Springboard","CA","31","Amazon"],
// ["Springboard","CA","20","Apple"],
// ["Springboard","CA","4","Bed Bath & Beyond"],
// ["Springboard","CA","8","Citi"],
// ["Springboard","CA","10","Deloitte"],
// ["Springboard","CA","20","Facebook"],
// ["Springboard","CA","13","Google"],
// ["Springboard","CA","6","Hack for LA"],
// ["Springboard","CA","8","IBM"],
// ["Springboard","CA","12","JPMorgan Chase & Co."],
// ["Springboard","CA","12","Wells Fargo"],
// ["Udacity","CA","208","Accenture"],
// ["Udacity","CA","368","Amazon"],
// ["Udacity","CA","146","Aramco"],
// ["Udacity","CA","206","Facebook"],
// ["Udacity","CA","150","Fiverr"],
// ["Udacity","CA","372","Google"],
// ["Udacity","CA","221","IBM"],
// ["Udacity","CA","174","Infosys"],
// ["Udacity","CA","306","Microsoft"],
// ["Udacity","CA","141","stc"],
// ["Udacity","CA","157","Tata Consultancy Services"],
// ["Udacity","CA","364","Upwork"],
// ["CodeCraft School of Technology","CO","1","AMP Robotics"],
// ["CodeCraft School of Technology","CO","1","Buink Web Development"],
// ["CodeCraft School of Technology","CO","3","Charter Communications"],
// ["CodeCraft School of Technology","CO","1","CUORE of Switzerland"],
// ["CodeCraft School of Technology","CO","1","EduGuide"],
// ["CodeCraft School of Technology","CO","1","Engrain"],
// ["CodeCraft School of Technology","CO","2","LogRhythm"],
// ["CodeCraft School of Technology","CO","1","Oracle"],
// ["CodeCraft School of Technology","CO","1","Simplified Website Design"],
// ["CodeCraft School of Technology","CO","1","Springboard"],
// ["CodeCraft School of Technology","CO","1","Town of Nederland"],
// ["CodeCraft School of Technology","CO","2","Trimble Inc."],
// ["CodeCraft School of Technology","CO","2","Zayo Group"],
// ["DaVinci Coders","CO","1","ClearanceJobs"],
// ["DaVinci Coders","CO","1","Corellian Consulting Limited"],
// ["DaVinci Coders","CO","1","EVO Payments Inc."],
// ["DaVinci Coders","CO","1","IBM"],
// ["DaVinci Coders","CO","1","Institutional Cash Distributors (ICD)"],
// ["DaVinci Coders","CO","1","JPMA Inc"],
// ["DaVinci Coders","CO","1","Kaffeinated Kodemonkey"],
// ["DaVinci Coders","CO","1","Literally Media"],
// ["DaVinci Coders","CO","1","Neap"],
// ["DaVinci Coders","CO","1","Nite Ize Inc."],
// ["DaVinci Coders","CO","1","Oracle"],
// ["DaVinci Coders","CO","2","RxRevu Inc."],
// ["DaVinci Coders","CO","1","Touch Control"],
// ["DaVinci Coders","CO","1","Triad"],
// ["SecureSet","CO","5","Avertium"],
// ["SecureSet","CO","6","Booz Allen Hamilton"],
// ["SecureSet","CO","9","Coalfire"],
// ["SecureSet","CO","5","Colorado Governor's Office of Information Technology"],
// ["SecureSet","CO","8","CyberGRX"],
// ["SecureSet","CO","8","deepwatch"],
// ["SecureSet","CO","4","Deloitte"],
// ["SecureSet","CO","12","Jacobs"],
// ["SecureSet","CO","8","Kivu Consulting"],
// ["SecureSet","CO","8","Pax8"],
// ["SecureSet","CO","6","ReliaQuest"],
// ["SecureSet","CO","32","US Army"],
// ["SecureSet","CO","5","VMware"],
// ["Skill Distillery","CO","2","Angi"],
// ["Skill Distillery","CO","2","Bank of America"],
// ["Skill Distillery","CO","3","BIT Systems"],
// ["Skill Distillery","CO","2","Booz Allen Hamilton"],
// ["Skill Distillery","CO","4","CACI International Inc"],
// ["Skill Distillery","CO","3","Charter Communications"],
// ["Skill Distillery","CO","6","Comcast"],
// ["Skill Distillery","CO","3","Essendant"],
// ["Skill Distillery","CO","3","HomeAdvisor"],
// ["Skill Distillery","CO","3","Ibotta Inc."],
// ["Skill Distillery","CO","6","NexGen Technologies Inc."],
// ["Skill Distillery","CO","3","Raytheon Intelligence & Space"],
// ["Skill Distillery","CO","2","Tech Mahindra"],
// ["Skill Distillery","CO","2","The Walt Disney Company"],
// ["Turing School of Software & Design","CO","21","Aetna"],
// ["Turing School of Software & Design","CO","17","Allstate"],
// ["Turing School of Software & Design","CO","6","Brandfolder"],
// ["Turing School of Software & Design","CO","17","Charter Communications"],
// ["Turing School of Software & Design","CO","7","Devetry (part of Dept)"],
// ["Turing School of Software & Design","CO","8","Fastly"],
// ["Turing School of Software & Design","CO","14","Guild Education"],
// ["Turing School of Software & Design","CO","7","Handshake"],
// ["Turing School of Software & Design","CO","9","Hotel Engine"],
// ["Turing School of Software & Design","CO","16","Ibotta Inc."],
// ["Turing School of Software & Design","CO","6","Peloton Interactive"],
// ["Turing School of Software & Design","CO","19","Slalom"],
// ["Turing School of Software & Design","CO","10","Stitch Fix"],
// ["Turing School of Software & Design","CO","7","TaxJar"],
// ["University of Denver Boot Camps","CO","1","acumen"],
// ["University of Denver Boot Camps","CO","1","Chevron"],
// ["University of Denver Boot Camps","CO","1","En Gedi"],
// ["University of Denver Boot Camps","CO","1","Hunger Free Colorado"],
// ["University of Denver Boot Camps","CO","1","Kärcher North America Inc."],
// ["University of Denver Boot Camps","CO","1","Rally Health"],
// ["University of Denver Boot Camps","CO","1","Scaled Agile Inc."],
// ["University of Denver Boot Camps","CO","1","Sealcon"],
// ["University of Denver Boot Camps","CO","1","SonderMind"],
// ["University of Denver Boot Camps","CO","2","uBreakiFix"],
// ["4Geeks Academy","FL","2","Boosmap"],
// ["4Geeks Academy","FL","2","Bridge Patient Portal"],
// ["4Geeks Academy","FL","2","Bridges Unite"],
// ["4Geeks Academy","FL","2","Cornershop by Uber"],
// ["4Geeks Academy","FL","3","DNA HUMAN CAPITAL"],
// ["4Geeks Academy","FL","2","Nivelat"],
// ["4Geeks Academy","FL","2","Patagonia IT"],
// ["4Geeks Academy","FL","2","The Dog Company Chile"],
// ["4Geeks Academy","FL","3","Uber"],
// ["4Geeks Academy","FL","3","University of Miami"],
// ["Wyncode Academy","FL","6","Apple"],
// ["Wyncode Academy","FL","4","Augusta Hitech"],
// ["Wyncode Academy","FL","9","BrainStation"],
// ["Wyncode Academy","FL","9","CareCloud"],
// ["Wyncode Academy","FL","6","Health Karma"],
// ["Wyncode Academy","FL","5","IntelePeer"],
// ["Wyncode Academy","FL","6","Kipu Health"],
// ["Wyncode Academy","FL","5","MDLIVE Inc."],
// ["Wyncode Academy","FL","5","Miami Dev Shop"],
// ["Wyncode Academy","FL","5","Microsoft"],
// ["Wyncode Academy","FL","5","Papa"],
// ["Wyncode Academy","FL","13","Restaurant Brands International"],
// ["Wyncode Academy","FL","5","springbig"],
// ["Wyncode Academy","FL","5","Watsco Ventures"],
// ["DigitalCrafts","GA","4","Accenture"],
// ["DigitalCrafts","GA","5","Chick-fil-A Corporate Support Center"],
// ["DigitalCrafts","GA","4","Codoxo"],
// ["DigitalCrafts","GA","4","Cox Automotive Inc."],
// ["DigitalCrafts","GA","8","Insiten"],
// ["DigitalCrafts","GA","5","JPMorgan Chase & Co."],
// ["DigitalCrafts","GA","4","Luminare Inc."],
// ["DigitalCrafts","GA","5","Mailchimp"],
// ["DigitalCrafts","GA","3","Microsoft"],
// ["DigitalCrafts","GA","12","The Home Depot"],
// ["DigitalCrafts","GA","6","Umbrage"],
// ["DigitalCrafts","GA","5","Varsity Hype"],
// ["DigitalCrafts","GA","6","Ware2Go"],
// ["DigitalCrafts","GA","4","WarnerMedia"],
// ["Georgia Tech Boot Camps","GA","1","XPO Logistics Inc."],
// ["CodeWorks","ID","1","Accenture"],
// ["CodeWorks","ID","1","Adobe"],
// ["CodeWorks","ID","2","Allata"],
// ["CodeWorks","ID","1","BGZ brands™"],
// ["CodeWorks","ID","3","Cask"],
// ["CodeWorks","ID","2","Definitive Logic"],
// ["CodeWorks","ID","8","In Time Tec"],
// ["CodeWorks","ID","1","Microbe Formulas"],
// ["CodeWorks","ID","1","P2 Energy Solutions"],
// ["CodeWorks","ID","1","TrueBlue Inc."],
// ["CodeWorks","ID","2","Western Power Sports (WPS)"],
// ["CodeWorks","ID","2","Zennify"],
// ["Actualize Coding Bootcamp","IL","2","Accenture"],
// ["Actualize Coding Bootcamp","IL","3","ActiveCampaign"],
// ["Actualize Coding Bootcamp","IL","3","AHEAD"],
// ["Actualize Coding Bootcamp","IL","2","AT&T"],
// ["Actualize Coding Bootcamp","IL","2","Boomerang Exhibits"],
// ["Actualize Coding Bootcamp","IL","2","Costco Wholesale"],
// ["Actualize Coding Bootcamp","IL","3","CVS Health"],
// ["Actualize Coding Bootcamp","IL","2","Datadog"],
// ["Actualize Coding Bootcamp","IL","2","Healthie Inc."],
// ["Actualize Coding Bootcamp","IL","3","Oracle"],
// ["Actualize Coding Bootcamp","IL","4","PayPal"],
// ["Actualize Coding Bootcamp","IL","7","The Difference Engine"],
// ["Code Platoon","IL","2","8th Light"],
// ["Code Platoon","IL","4","Army National Guard"],
// ["Code Platoon","IL","4","Army National Guard"],
// ["Code Platoon","IL","1","Cartão de Todos"],
// ["Code Platoon","IL","3","Chicago Trading Company"],
// ["Code Platoon","IL","1","Codementor"],
// ["Code Platoon","IL","7","DRW"],
// ["Code Platoon","IL","2","Enova International"],
// ["Code Platoon","IL","2","Grainger"],
// ["Code Platoon","IL","7","JPMorgan Chase & Co."],
// ["Code Platoon","IL","2","Motorola Solutions"],
// ["Code Platoon","IL","2","Raise"],
// ["Code Platoon","IL","6","United States Air Force"],
// ["Code Platoon","IL","6","US Army"],
// ["Code Platoon","IL","4","US Navy"],
// ["Coding Temple","IL","1","Accenture"],
// ["Coding Temple","IL","1","Amazon"],
// ["Coding Temple","IL","1","Beyond Finance"],
// ["Coding Temple","IL","1","Birchwood Foods"],
// ["Coding Temple","IL","1","Booz Allen Hamilton"],
// ["Coding Temple","IL","1","Capgemini"],
// ["Coding Temple","IL","1","City Colleges of Chicago-Olive-Harvey College"],
// ["Coding Temple","IL","1","Convoy Inc"],
// ["Coding Temple","IL","1","Copado"],
// ["Coding Temple","IL","1","Datadog"],
// ["Coding Temple","IL","1","Numerated"],
// ["Coding Temple","IL","1","SORACOM Inc."],
// ["Coding Temple","IL","1","U.S. Navy Reserve"],
// ["Coding Temple","IL","2","Upwork"],
// ["Eleven Fifty Academy","IN","4","Agilify Automation"],
// ["Eleven Fifty Academy","IN","3","Community Health Network"],
// ["Eleven Fifty Academy","IN","4","DMI (Digital Management LLC)"],
// ["Eleven Fifty Academy","IN","4","DoorDash"],
// ["Eleven Fifty Academy","IN","8","GEICO"],
// ["Eleven Fifty Academy","IN","12","Infosys"],
// ["Eleven Fifty Academy","IN","4","Ion Three"],
// ["Eleven Fifty Academy","IN","4","Liberty Mutual Insurance"],
// ["Eleven Fifty Academy","IN","4","Navient"],
// ["Eleven Fifty Academy","IN","6","Offprem Technology"],
// ["Eleven Fifty Academy","IN","7","R&M Software Inc."],
// ["Eleven Fifty Academy","IN","7","Salesforce"],
// ["Eleven Fifty Academy","IN","6","TCC Software Solutions"],
// ["Eleven Fifty Academy","IN","4","US Army"],
// ["Kenzie Academy","IN","136","Amazon"],
// ["Kenzie Academy","IN","16","Amazon Fulfillment Centre"],
// ["Kenzie Academy","IN","4","Amazon Logistics"],
// ["Kenzie Academy","IN","2","AT&T"],
// ["Kenzie Academy","IN","2","Career Karma"],
// ["Kenzie Academy","IN","3","DMI (Digital Management LLC)"],
// ["Kenzie Academy","IN","2","FedEx Ground"],
// ["Kenzie Academy","IN","2","Infosys"],
// ["Kenzie Academy","IN","4","Infosys Ltd"],
// ["Kenzie Academy","IN","2","JPMorgan Chase & Co."],
// ["Kenzie Academy","IN","2","KellyConnect | Contact Center Solutions"],
// ["Kenzie Academy","IN","8","Southern New Hampshire University"],
// ["Kenzie Academy","IN","2","SuperWorld"],
// ["Kenzie Academy","IN","2","Zylo"],
// ["Awesome Inc","KY","4","APAX Software"],
// ["Awesome Inc","KY","2","Bitwerx Inc."],
// ["Awesome Inc","KY","2","BlueFrame Technology"],
// ["Awesome Inc","KY","1","CSI"],
// ["Awesome Inc","KY","1","Infosys"],
// ["Awesome Inc","KY","1","Kentucky Department of Revenue"],
// ["Awesome Inc","KY","2","Lightwell Inc."],
// ["Awesome Inc","KY","3","Nymbl Systems"],
// ["Awesome Inc","KY","1","OmniLife"],
// ["Awesome Inc","KY","1","Rev.com"],
// ["Awesome Inc","KY","2","Starbucks"],
// ["Awesome Inc","KY","2","Studio 34 Productions"],
// ["Code Louisville","KY","8","Appriss"],
// ["Code Louisville","KY","7","Atria Senior Living"],
// ["Code Louisville","KY","9","El Toro IP Targeting"],
// ["Code Louisville","KY","14","GE Appliances"],
// ["Code Louisville","KY","33","Humana"],
// ["Code Louisville","KY","11","Jefferson County Public Schools"],
// ["Code Louisville","KY","6","Kroger"],
// ["Code Louisville","KY","6","QSR Automations"],
// ["Code Louisville","KY","5","Rainbow Design Services Inc."],
// ["Code Louisville","KY","6","University of Louisville"],
// ["Code Louisville","KY","18","UPS"],
// ["Code Louisville","KY","12","Waystar"],
// ["Practicum by Yandex","MA","3","GlowByte Consulting"],
// ["Practicum by Yandex","MA","3","Infosys"],
// ["Practicum by Yandex","MA","3","JPMorgan Chase & Co."],
// ["Practicum by Yandex","MA","4","OZON.ru"],
// ["Practicum by Yandex","MA","3","Rostelecom"],
// ["Practicum by Yandex","MA","5","Sberbank"],
// ["Practicum by Yandex","MA","3","uTest"],
// ["Practicum by Yandex","MA","3","X5 Retail Group"],
// ["Grand Circus","MI","20","Accenture"],
// ["Grand Circus","MI","18","Amrock"],
// ["Grand Circus","MI","11","Blue Cross Blue Shield of Michigan"],
// ["Grand Circus","MI","16","Detroit Labs"],
// ["Grand Circus","MI","7","Detroit Public Schools Community District"],
// ["Grand Circus","MI","16","Ford Motor Company"],
// ["Grand Circus","MI","8","Meridian"],
// ["Grand Circus","MI","8","MRM"],
// ["Grand Circus","MI","30","Nexient"],
// ["Grand Circus","MI","7","Perficient"],
// ["Grand Circus","MI","87","Quicken Loans"],
// ["Grand Circus","MI","7","Spectrum Health"],
// ["Grand Circus","MI","11","United Shore"],
// ["Grand Circus","MI","84","United Wholesale Mortgage"],
// ["Prime Digital Academy","MN","11","Accessible360"],
// ["Prime Digital Academy","MN","38","Best Buy"],
// ["Prime Digital Academy","MN","25","C.H. Robinson"],
// ["Prime Digital Academy","MN","12","Datasite"],
// ["Prime Digital Academy","MN","7","Daugherty Business Solutions"],
// ["Prime Digital Academy","MN","10","Granicus"],
// ["Prime Digital Academy","MN","13","Optum"],
// ["Prime Digital Academy","MN","7","Slalom"],
// ["Prime Digital Academy","MN","11","SPS Commerce"],
// ["Prime Digital Academy","MN","38","Target"],
// ["Prime Digital Academy","MN","16","Thomson Reuters"],
// ["Prime Digital Academy","MN","11","Total Expert"],
// ["Prime Digital Academy","MN","19","Travelers"],
// ["Prime Digital Academy","MN","8","U.S. Bank"],
// ["Claim Academy","MO","4","Accenture Federal Services"],
// ["Claim Academy","MO","2","Army National Guard"],
// ["Claim Academy","MO","3","Best Buy"],
// ["Claim Academy","MO","6","Charter Communications"],
// ["Claim Academy","MO","5","GalaxE.Solutions"],
// ["Claim Academy","MO","3","LaunchCode"],
// ["Claim Academy","MO","4","Mastercard"],
// ["Claim Academy","MO","5","NISA Investment Advisors LLC"],
// ["Claim Academy","MO","3","Perficient"],
// ["Claim Academy","MO","2","Revature"],
// ["Claim Academy","MO","3","Slalom"],
// ["Claim Academy","MO","2","US Army"],
// ["Claim Academy","MO","3","Washington University in St. Louis"],
// ["Momentum","NC","4","Alberta Health Services"],
// ["Momentum","NC","3","Discovery Limited"],
// ["Momentum","NC","3","IBM"],
// ["Momentum","NC","2","Infosys"],
// ["Momentum","NC","2","JPMorgan Chase & Co."],
// ["Momentum","NC","5","Pendo.io"],
// ["Momentum","NC","3","Salesforce"],
// ["Momentum","NC","2","SciMed Solutions Inc."],
// ["Momentum","NC","3","ServiceTrade"],
// ["Momentum","NC","4","Spreedly"],
// ["Momentum","NC","2","Westcan Bulk Transport"],
// ["RMOTR","NC","1","APEX Drone Racing"],
// ["RMOTR","NC","1","Bank of America"],
// ["RMOTR","NC","1","Fitbit (now part of Google)"],
// ["RMOTR","NC","1","How-To Geek"],
// ["RMOTR","NC","1","Intel Corporation"],
// ["RMOTR","NC","1","JPMorgan Chase & Co."],
// ["RMOTR","NC","1","Milestone Digital"],
// ["RMOTR","NC","1","Norges Bank Investment Management"],
// ["RMOTR","NC","1","Satellogic"],
// ["RMOTR","NC","1","Shelley Automation"],
// ["RMOTR","NC","1","Skytree | A Fresh Breath of Air"],
// ["RMOTR","NC","1","US Army"],
// ["RMOTR","NC","1","Verizon"],
// ["RMOTR","NC","2","Zynga"],
// ["Emerging Digital Academy","ND","1","701x"],
// ["Emerging Digital Academy","ND","1","Auto Doctors LLC"],
// ["Emerging Digital Academy","ND","1","BNG Team"],
// ["Emerging Digital Academy","ND","2","Bushel"],
// ["Emerging Digital Academy","ND","1","ByteSpeed"],
// ["Emerging Digital Academy","ND","1","Creatively Web Design & Development"],
// ["Emerging Digital Academy","ND","1","eXp Realty"],
// ["Emerging Digital Academy","ND","1","Learn Or Teach LLC"],
// ["Emerging Digital Academy","ND","1","Penta Blockchain Solutions"],
// ["Emerging Digital Academy","ND","2","Project Phoenix"],
// ["Emerging Digital Academy","ND","3","Scheels"],
// ["Emerging Digital Academy","ND","1","Social Selling HQ"],
// ["UNH Coding Boot Camp","NH","1","Comcast Business"],
// ["UNH Coding Boot Camp","NH","1","Fidelity Investments"],
// ["UNH Coding Boot Camp","NH","1","IANS"],
// ["UNH Coding Boot Camp","NH","1","Known Point Technologies"],
// ["UNH Coding Boot Camp","NH","2","Liberty Mutual Insurance"],
// ["UNH Coding Boot Camp","NH","1","Loud Canvas Media"],
// ["Rutgers Bootcamps","NJ","1","Amazon"],
// ["Rutgers Bootcamps","NJ","1","Banfield Pet Hospital"],
// ["Rutgers Bootcamps","NJ","1","Bizzabo"],
// ["Rutgers Bootcamps","NJ","1","Incyte Studios"],
// ["Rutgers Bootcamps","NJ","1","PTC Therapeutics"],
// ["Rutgers Bootcamps","NJ","1","Robert Wood Johnson University Hospital"],
// ["App Academy","NY","22","Amazon"],
// ["App Academy","NY","37","Bloomberg LP"],
// ["App Academy","NY","8","DailyPay Inc."],
// ["App Academy","NY","7","Etsy"],
// ["App Academy","NY","38","Facebook"],
// ["App Academy","NY","86","Google"],
// ["App Academy","NY","18","Medidata Solutions"],
// ["App Academy","NY","5","New Relic Inc."],
// ["App Academy","NY","7","Samsara"],
// ["App Academy","NY","8","Twitter"],
// ["App Academy","NY","14","Uber"],
// ["App Academy","NY","10","Upwork"],
// ["App Academy","NY","42","Wayfair"],
// ["App Academy","NY","10","Zendesk"],
// ["BrainStation","NY","26","BMO Financial Group"],
// ["BrainStation","NY","33","Canadian Tire Corporation"],
// ["BrainStation","NY","55","CIBC"],
// ["BrainStation","NY","21","Hootsuite"],
// ["BrainStation","NY","45","Konrad Group"],
// ["BrainStation","NY","15","Loblaw Digital"],
// ["BrainStation","NY","33","lululemon"],
// ["BrainStation","NY","66","RBC"],
// ["BrainStation","NY","22","Rogers Sports & Media"],
// ["BrainStation","NY","49","Scotiabank"],
// ["BrainStation","NY","80","Shopify"],
// ["BrainStation","NY","47","TD"],
// ["BrainStation","NY","41","TELUS"],
// ["BrainStation","NY","19","The University of British Columbia"],
// ["Byte Academy","NY","2","Absa Group"],
// ["Byte Academy","NY","1","BACKED VC"],
// ["Byte Academy","NY","1","Capital Rx"],
// ["Byte Academy","NY","1","College Truckers Inc."],
// ["Byte Academy","NY","2","Geodesic Techniques"],
// ["Byte Academy","NY","1","IBM"],
// ["Byte Academy","NY","5","JPMorgan Chase & Co."],
// ["Byte Academy","NY","3","NOV"],
// ["Byte Academy","NY","1","Oracle"],
// ["Byte Academy","NY","8","SpryteLabs"],
// ["Byte Academy","NY","1","Tempus Labs Inc."],
// ["Byte Academy","NY","1","Torus Teens"],
// ["Flatiron School","NY","27","Accenture"],
// ["Flatiron School","NY","44","Amazon"],
// ["Flatiron School","NY","21","Citi"],
// ["Flatiron School","NY","37","Datadog"],
// ["Flatiron School","NY","31","IBM"],
// ["Flatiron School","NY","128","Infosys"],
// ["Flatiron School","NY","41","JPMorgan Chase & Co."],
// ["Flatiron School","NY","10","Shopify"],
// ["Flatiron School","NY","16","Spotify"],
// ["Flatiron School","NY","15","The New York Times"],
// ["Flatiron School","NY","23","Wayfair"],
// ["Flatiron School","NY","23","WeWork"],
// ["Fullstack Academy","NY","18","Amazon"],
// ["Fullstack Academy","NY","25","American Express"],
// ["Fullstack Academy","NY","9","BlackRock"],
// ["Fullstack Academy","NY","67","Bloomberg LP"],
// ["Fullstack Academy","NY","20","Etsy"],
// ["Fullstack Academy","NY","11","Goldman Sachs"],
// ["Fullstack Academy","NY","45","Google"],
// ["Fullstack Academy","NY","26","JPMorgan Chase & Co."],
// ["Fullstack Academy","NY","15","Northwestern Mutual"],
// ["Fullstack Academy","NY","16","Spotify"],
// ["Fullstack Academy","NY","14","The New York Times"],
// ["Fullstack Academy","NY","8","Wunderkind (Formerly BounceX)"],
// ["General Assembly","NY","134","Accenture"],
// ["General Assembly","NY","101","Adobe"],
// ["General Assembly","NY","235","Amazon"],
// ["General Assembly","NY","94","Amazon Web Services (AWS)"],
// ["General Assembly","NY","152","Apple"],
// ["General Assembly","NY","62","Atlassian"],
// ["General Assembly","NY","181","Booz Allen Hamilton"],
// ["General Assembly","NY","243","Facebook"],
// ["General Assembly","NY","383","Google"],
// ["General Assembly","NY","149","IBM"],
// ["General Assembly","NY","78","LinkedIn"],
// ["General Assembly","NY","151","Microsoft"],
// ["General Assembly","NY","108","Salesforce"],
// ["General Assembly","NY","71","Spotify"],
// ["Metis","NY","4","Amazon"],
// ["Metis","NY","2","Bank of America"],
// ["Metis","NY","2","Citi"],
// ["Metis","NY","2","City of Amsterdam"],
// ["Metis","NY","2","Comcast"],
// ["Metis","NY","2","Disney Streaming Services"],
// ["Metis","NY","4","Facebook"],
// ["Metis","NY","3","Google"],
// ["Metis","NY","3","IBM"],
// ["Metis","NY","2","Tempus Labs Inc. "],
// ["Metis","NY","4","The Spur Group"],
// ["Metis","NY","2","Trilogy Education"],
// ["Metis","NY","2","Uber"],
// ["Metis","NY","2","Warwick Investment Group"],
// ["New York Code + Design Academy","NY","4","ABN AMRO Bank N.V."],
// ["New York Code + Design Academy","NY","4","Apple"],
// ["New York Code + Design Academy","NY","3","Capgemini"],
// ["New York Code + Design Academy","NY","3","Cognizant"],
// ["New York Code + Design Academy","NY","5","Comcast"],
// ["New York Code + Design Academy","NY","3","Gartner"],
// ["New York Code + Design Academy","NY","5","Google"],
// ["New York Code + Design Academy","NY","4","Incentro"],
// ["New York Code + Design Academy","NY","7","IntuitSolutions"],
// ["New York Code + Design Academy","NY","3","LinkedIn"],
// ["New York Code + Design Academy","NY","3","NYC Department of Education"],
// ["New York Code + Design Academy","NY","3","University of Pennsylvania"],
// ["Noble Desktop","NY","4","Apple"],
// ["Noble Desktop","NY","2","Conscience VC"],
// ["Noble Desktop","NY","3","FCB Health"],
// ["Noble Desktop","NY","2","Hachette Book Group"],
// ["Noble Desktop","NY","2","IBM"],
// ["Noble Desktop","NY","2","JPMorgan Chase & Co."],
// ["Noble Desktop","NY","2","Meredith Corporation"],
// ["Noble Desktop","NY","2","Penguin Random House"],
// ["Noble Desktop","NY","2","Pratt Institute"],
// ["Noble Desktop","NY","2","Rodale Inc."],
// ["Noble Desktop","NY","4","Scholastic"],
// ["Noble Desktop","NY","2","The Conference Board"],
// ["Noble Desktop","NY","3","Upwork"],
// ["Noble Desktop","NY","2","Verizon"],
// ["Skillcrush","NY","3","CVS Health"],
// ["Skillcrush","NY","2","Flatiron School"],
// ["Skillcrush","NY","2","Independent Consultant"],
// ["Skillcrush","NY","2","lululemon"],
// ["Skillcrush","NY","2","Lyft"],
// ["Skillcrush","NY","2","Stitch Fix"],
// ["Skillcrush","NY","2","T-Mobile"],
// ["Skillcrush","NY","3","U.S. Department of Veterans Affairs"],
// ["Skillcrush","NY","2","Ulta Beauty"],
// ["Skillcrush","NY","6","VIPKid"],
// ["Skillcrush","NY","2","Zapier"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Annalect"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Attentive"],
// ["The Grace Hopper Program at Fullstack Academy","NY","7","Bloomberg LP"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Bounteous"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Datadog"],
// ["The Grace Hopper Program at Fullstack Academy","NY","3","Etsy"],
// ["The Grace Hopper Program at Fullstack Academy","NY","4","Fullstack Academy"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Goldman Sachs"],
// ["The Grace Hopper Program at Fullstack Academy","NY","4","Google"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","Northwestern Mutual"],
// ["The Grace Hopper Program at Fullstack Academy","NY","2","T-Mobile"],
// ["The Grace Hopper Program at Fullstack Academy","NY","3","Unqork"],
// ["Thinkful","NY","21","Amazon"],
// ["Thinkful","NY","3","Anant"],
// ["Thinkful","NY","2","Finix"],
// ["Thinkful","NY","4","Fiverr"],
// ["Thinkful","NY","3","Hack for LA"],
// ["Thinkful","NY","3","HubSpot"],
// ["Thinkful","NY","8","IBM"],
// ["Thinkful","NY","4","Personal Projects"],
// ["Thinkful","NY","10","Trilogy Education"],
// ["Thinkful","NY","7","Upwork"],
// ["Thinkful","NY","3","Walmart Global Tech"],
// ["MAX Technical Training & Career Programs","OH","1","Bottom Line Systems"],
// ["MAX Technical Training & Career Programs","OH","1","Eurostampa North America Inc."],
// ["MAX Technical Training & Career Programs","OH","2","Great American Insurance Group"],
// ["MAX Technical Training & Career Programs","OH","1","IBM"],
// ["MAX Technical Training & Career Programs","OH","1","K-Electric"],
// ["MAX Technical Training & Career Programs","OH","4","Kroger Technology"],
// ["MAX Technical Training & Career Programs","OH","2","Matthews Automation Solutions"],
// ["MAX Technical Training & Career Programs","OH","1","Ohio National Financial Services"],
// ["MAX Technical Training & Career Programs","OH","3","Procter & Gamble"],
// ["MAX Technical Training & Career Programs","OH","1","Seven Hills Technology"],
// ["MAX Technical Training & Career Programs","OH","1","Shoptech Software - Manufacturing Software"],
// ["MAX Technical Training & Career Programs","OH","1","The Cincinnati Insurance Companies"],
// ["MAX Technical Training & Career Programs","OH","1","Top Gun Sales Performance"],
// ["MAX Technical Training & Career Programs","OH","2","Total Quality Logistics"],
// ["Tech Elevator","OH","12","AmTrust Financial Services Inc."],
// ["Tech Elevator","OH","20","BNY Mellon"],
// ["Tech Elevator","OH","11","DICK'S Sporting Goods"],
// ["Tech Elevator","OH","10","Edaptive Computing Inc."],
// ["Tech Elevator","OH","13","Fifth Third Bank"],
// ["Tech Elevator","OH","138","JPMorgan Chase & Co."],
// ["Tech Elevator","OH","14","KeyBank"],
// ["Tech Elevator","OH","17","London Computer Systems"],
// ["Tech Elevator","OH","39","National General Insurance"],
// ["Tech Elevator","OH","18","Nationwide"],
// ["Tech Elevator","OH","21","Olive"],
// ["Tech Elevator","OH","243","PNC"],
// ["Tech Elevator","OH","34","Progressive Insurance"],
// ["Tech Elevator","OH","15","United Wholesale Mortgage"],
// ["We Can Code IT","OH","5","Acumen Solutions"],
// ["We Can Code IT","OH","3","Apple"],
// ["We Can Code IT","OH","4","Cardinal Health"],
// ["We Can Code IT","OH","3","CoverMyMeds"],
// ["We Can Code IT","OH","4","Foundation Software"],
// ["We Can Code IT","OH","6","Huntington National Bank"],
// ["We Can Code IT","OH","23","JPMorgan Chase & Co."],
// ["We Can Code IT","OH","4","KeyBank"],
// ["We Can Code IT","OH","3","MoreSteam"],
// ["We Can Code IT","OH","5","National General Insurance"],
// ["We Can Code IT","OH","6","Nationwide"],
// ["We Can Code IT","OH","9","PNC"],
// ["We Can Code IT","OH","14","Progressive Insurance"],
// ["We Can Code IT","OH","4","Root Inc."],
// ["Alchemy Code Lab","OR","3","Adobe"],
// ["Alchemy Code Lab","OR","2","Allocations"],
// ["Alchemy Code Lab","OR","2","Emsi"],
// ["Alchemy Code Lab","OR","2","Esri"],
// ["Alchemy Code Lab","OR","1","EventBuilder"],
// ["Alchemy Code Lab","OR","2","Hatch Data"],
// ["Alchemy Code Lab","OR","2","HealthSparq"],
// ["Alchemy Code Lab","OR","3","Kinship"],
// ["Alchemy Code Lab","OR","2","Kroger Technology"],
// ["Alchemy Code Lab","OR","5","Lithia Motors"],
// ["Alchemy Code Lab","OR","4","Nike"],
// ["Alchemy Code Lab","OR","2","Schoolhouse"],
// ["Alchemy Code Lab","OR","5","Sprinklr"],
// ["Alchemy Code Lab","OR","2","Squishymedia"],
// ["Epicodus","OR","6","Ascend Software"],
// ["Epicodus","OR","7","EyeCue Lab"],
// ["Epicodus","OR","4","Goalden Hour"],
// ["Epicodus","OR","3","Hubb"],
// ["Epicodus","OR","4","iGrafx"],
// ["Epicodus","OR","3","Microsoft Leap Apprenticeship Program"],
// ["Epicodus","OR","3","National Society of Black Engineers"],
// ["Epicodus","OR","6","New Relic Inc."],
// ["Epicodus","OR","6","Nike"],
// ["Epicodus","OR","8","Nombolo"],
// ["Epicodus","OR","3","PDXR"],
// ["Epicodus","OR","3","Pollinate"],
// ["Epicodus","OR","3","Tuft & Needle"],
// ["Epicodus","OR","5","UGrow"],
// ["The Tech Academy","OR","2","Adobe"],
// ["The Tech Academy","OR","3","Amazon"],
// ["The Tech Academy","OR","3","Conduent"],
// ["The Tech Academy","OR","2","Epiq"],
// ["The Tech Academy","OR","4","Intel Corporation"],
// ["The Tech Academy","OR","6","Microsoft"],
// ["The Tech Academy","OR","5","New Relic Inc."],
// ["The Tech Academy","OR","4","Nike"],
// ["The Tech Academy","OR","2","Novus Labs"],
// ["The Tech Academy","OR","28","Prosper I.T. Consulting"],
// ["The Tech Academy","OR","2","Smarsh"],
// ["The Tech Academy","OR","2","The Home Depot"],
// ["Academy Pittsburgh","PA","1","Advanced Computer & Network Corp. (AC&NC) JetStor"],
// ["Academy Pittsburgh","PA","1","Behaivior"],
// ["Academy Pittsburgh","PA","1","Build412 Tech"],
// ["Academy Pittsburgh","PA","1","CoverMyMeds"],
// ["Academy Pittsburgh","PA","3","numo llc"],
// ["Academy Pittsburgh","PA","5","PNC"],
// ["Academy Pittsburgh","PA","1","Seeking a New Opportunity"],
// ["Academy Pittsburgh","PA","1","Sparkbox"],
// ["Academy Pittsburgh","PA","1","Velocity Works"],
// ["Academy Pittsburgh","PA","1","Work Hard Solutions"],
// ["Nashville Software School","TN","39","Accenture"],
// ["Nashville Software School","TN","11","AllianceBernstein"],
// ["Nashville Software School","TN","10","Aspire Health Inc."],
// ["Nashville Software School","TN","18","Built Technologies"],
// ["Nashville Software School","TN","12","FortyAU"],
// ["Nashville Software School","TN","16","HCA Healthcare"],
// ["Nashville Software School","TN","13","Healthcare Bluebook"],
// ["Nashville Software School","TN","13","HealthStream"],
// ["Nashville Software School","TN","10","National General Insurance"],
// ["Nashville Software School","TN","9","naviHealth"],
// ["Nashville Software School","TN","10","Ncontracts"],
// ["Nashville Software School","TN","13","Ramsey Solutions"],
// ["Nashville Software School","TN","9","Tennessee Department of Transportation"],
// ["Nashville Software School","TN","12","Vanderbilt University Medical Center"],
// ["Codeup","TX","17","Accenture"],
// ["Codeup","TX","31","Accenture Federal Services"],
// ["Codeup","TX","20","Appddiction Studio"],
// ["Codeup","TX","8","Booz Allen Hamilton"],
// ["Codeup","TX","9","CaptureRx"],
// ["Codeup","TX","13","Cognizant"],
// ["Codeup","TX","9","Guardian Premier Solutions (GPS) LLC"],
// ["Codeup","TX","9","H-E-B"],
// ["Codeup","TX","5","Silotech Group Inc"],
// ["Codeup","TX","10","SWBC"],
// ["Codeup","TX","6","TaskUs"],
// ["Codeup","TX","47","USAA"],
// ["Inventive Academy","TX","1","Darwin Homes - Property Management"],
// ["Inventive Academy","TX","1","eCommission"],
// ["Inventive Academy","TX","1","Graafschap College"],
// ["Inventive Academy","TX","1","InstiWitty Media Studios"],
// ["Inventive Academy","TX","1","Itzu Jobs"],
// ["Inventive Academy","TX","1","MB Aerospace"],
// ["Inventive Academy","TX","1","Mindtree"],
// ["Inventive Academy","TX","1","Point Security LLC"],
// ["Inventive Academy","TX","1","Polamer Precision Inc."],
// ["Inventive Academy","TX","2","RepHQ LLC"],
// ["Inventive Academy","TX","1","Subh Muhurat"],
// ["UT Austin Boot Camps","TX","1","Digital Pharmacist Inc."],
// ["UT Austin Boot Camps","TX","1","Siemens"],
// ["UT Austin Boot Camps","TX","1","Visio Lending"],
// ["Bottega Career Services","UT","3","Alder Holdings LLC"],
// ["Bottega Career Services","UT","5","Amazon"],
// ["Bottega Career Services","UT","3","Avii"],
// ["Bottega Career Services","UT","4","Coforge"],
// ["Bottega Career Services","UT","6","Conscience VC"],
// ["Bottega Career Services","UT","4","Dev Pipeline"],
// ["Bottega Career Services","UT","3","Edge by Ascential"],
// ["Bottega Career Services","UT","3","Hoverstate"],
// ["Bottega Career Services","UT","3","MX"],
// ["Bottega Career Services","UT","4","Upwork"],
// ["Devmountain","UT","14","Divvy | Inc."],
// ["Devmountain","UT","22","MX"],
// ["Devmountain","UT","16","Overstock.com"],
// ["Devmountain","UT","18","Pluralsight"],
// ["Devmountain","UT","25","Podium"],
// ["Devmountain","UT","8","projekt202"],
// ["Devmountain","UT","6","TCN"],
// ["Devmountain","UT","17","The Church of Jesus Christ of Latter-day Saints"],
// ["Devmountain","UT","7","Veryable"],
// ["Devmountain","UT","14","Vivint"],
// ["Devmountain","UT","7","Workfront"],
// ["DevPoint Labs","UT","4","Acima Credit"],
// ["DevPoint Labs","UT","3","ARUP Laboratories"],
// ["DevPoint Labs","UT","3","Direct®"],
// ["DevPoint Labs","UT","3","Divvy | Inc."],
// ["DevPoint Labs","UT","3","ExpertVoice"],
// ["DevPoint Labs","UT","3","Fidelity Investments"],
// ["DevPoint Labs","UT","3","Goldman Sachs"],
// ["DevPoint Labs","UT","3","Instructure"],
// ["DevPoint Labs","UT","3","Mavenlink"],
// ["DevPoint Labs","UT","5","MX"],
// ["DevPoint Labs","UT","3","Nav Inc."],
// ["DevPoint Labs","UT","3","Shareworks by Morgan Stanley"],
// ["DevPoint Labs","UT","3","The Church of Jesus Christ of Latter-day Saints"],
// ["DevPoint Labs","UT","6","Verisys Corporation"],
// ["V School","UT","9","Adobe"],
// ["V School","UT","3","Conscience VC"],
// ["V School","UT","4","Divvy | Inc."],
// ["V School","UT","3","Fidelity Investments"],
// ["V School","UT","2","IBM"],
// ["V School","UT","2","Impartner Software"],
// ["V School","UT","3","O.C. Tanner"],
// ["V School","UT","4","Smash Creative"],
// ["V School","UT","3","Verisage Custom Software"],
// ["V School","UT","3","VMware"],
// ["V School","UT","2","Weave HQ"],
// ["V School","UT","3","XANT"],
// ["Burlington Code Academy","VT","2","Asure Software"],
// ["Burlington Code Academy","VT","1","Burton Snowboards"],
// ["Burlington Code Academy","VT","4","Dealer.com"],
// ["Burlington Code Academy","VT","1","EZ-Probate Inc."],
// ["Burlington Code Academy","VT","1","Impulse Creative"],
// ["Burlington Code Academy","VT","1","Jay Peak Resort"],
// ["Burlington Code Academy","VT","2","New Breed"],
// ["Burlington Code Academy","VT","3","oK"],
// ["Burlington Code Academy","VT","2","Select Design"],
// ["Burlington Code Academy","VT","1","trUStr ®"],
// ["Burlington Code Academy","VT","1","Vermont Systems"],
// ["Code Fellows","WA","6","Abdul Aziz Al Ghurair School of Advanced Computing (ASAC)"],
// ["Code Fellows","WA","48","Amazon"],
// ["Code Fellows","WA","42","Amazon Web Services (AWS)"],
// ["Code Fellows","WA","13","Avalara"],
// ["Code Fellows","WA","13","Expedia Group"],
// ["Code Fellows","WA","7","F5"],
// ["Code Fellows","WA","100","Microsoft"],
// ["Code Fellows","WA","7","Nike"],
// ["Code Fellows","WA","11","Nordstrom"],
// ["Code Fellows","WA","7","SAP Concur"],
// ["Code Fellows","WA","8","Slalom Build"],
// ["Code Fellows","WA","6","Smartsheet"],
// ["Code Fellows","WA","9","US Army"],
// ["Code Fellows","WA","10","Zonar Systems"],
// ["Coding Dojo","WA","13","Accenture"],
// ["Coding Dojo","WA","52","Amazon"],
// ["Coding Dojo","WA","14","Amazon Web Services (AWS)"],
// ["Coding Dojo","WA","10","Conscience VC"],
// ["Coding Dojo","WA","11","Google"],
// ["Coding Dojo","WA","10","Infosys"],
// ["Coding Dojo","WA","53","Microsoft"],
// ["Coding Dojo","WA","9","Mindtree"],
// ["Coding Dojo","WA","5","The Difference Engine"],
// ["Coding Dojo","WA","8","Upwork"],
// ["Coding Dojo","WA","12","US Army"],
// ["Nucamp Coding Bootcamp","WA","8","Amazon"],
// ["Nucamp Coding Bootcamp","WA","3","Apple"],
// ["Nucamp Coding Bootcamp","WA","3","Infosys"],
// ["Nucamp Coding Bootcamp","WA","9","Microsoft"],
// ["Nucamp Coding Bootcamp","WA","3","TEKsystems"],
// ["Nucamp Coding Bootcamp","WA","3","United States Air Force"],
// ["Nucamp Coding Bootcamp","WA","3","US Army"],
// ["Nucamp Coding Bootcamp","WA","3","Verizon"],
// ["Nucamp Coding Bootcamp","WA","3","Walgreens"],
// ["Nucamp Coding Bootcamp","WA","3","Walmart"],
// ["The Array School of Technology and Design","WY","2","Advent Information Systems L.L.C."],
// ["The Array School of Technology and Design","WY","1","Campbell County Public Library System"],
// ["The Array School of Technology and Design","WY","1","Holland & Hart LLP"],
// ["The Array School of Technology and Design","WY","1","Laramie County Library System"],
// ["The Array School of Technology and Design","WY","1","Medicine Bow Technologies Inc."],
// ["The Array School of Technology and Design","WY","1","PBR MARKETING & PRINTING SOLUTIONS"],
// ["The Array School of Technology and Design","WY","1","State of Wyoming"],
// ["The Array School of Technology and Design","WY","1","The TJX Companies Inc."],
// ["The Array School of Technology and Design","WY","1","University of Wyoming"]];

// let final = {
//     name: 'states',
//     children: [
//         {
//             name: 'WA',
//             children: [
//                 {
//                     name: 'Nucamp Coding Bootcamp',
//                     children: [
//                         {
//                             name: 'Walgreens',
//                             value: 3
//                         }
//                     ]
//                 }
//             ]
//         }
//     ]
// }

let data = {
    name: 'states',
    children: []
};

let c = 0;

async function buildCompanies (c, currentCompanies, campIndex) {
    console.log("Called 3rd function")
    let datums = {...currentCompanies}
    return datums
}

let b = 0;
let countedBootcamps = [];
let currentCompanies = [];
let prevBootcamp = "";
let stateData = [];

async function buildBootcamps(b, currentBootcamps, prevBootcamp, countedBootcamps) {
    currentData = currentBootcamps[b];
    // console.log (currentData)
    let currentBootcamp = currentData[0];
    if(countedBootcamps.includes(currentBootcamp) === false) {
        countedBootcamps.push(currentBootcamp)
        // data.children[stateIndex].children.push({name: currentBootcamp, children: []})
        stateData.push({name: currentBootcamp, children: []})
        console.log("counted bootcamps", countedBootcamps)
    }
    if(currentBootcamp === prevBootcamp) {
        currentCompanies.push(currentData);
    } else {
        let campIndex = countedBootcamps.indexOf(prevBootcamp);
        let returnedArray = buildCompanies(c, currentCompanies, campIndex);
        prevBootcamp = currentBootcamp;
        currentCompanies = [];
        stateData[campIndex].children.push(...returnedArray);
    }
    b++;
    if (b < currentBootcamps.length) {
        console.log(b, "recusion!");
        buildBootcamps(b, currentBootcamps, prevBootcamp, countedBootcamps)
    } else {
        // console.log("pushed bootcamps ", b)
        return stateData;
    }
    
    
    
    // data.children[stateIndex].children.push(bootcamps)
}

let a = 0;
let currentData = grads[a];
let prevState = currentData[1];
let countedStates = [];
let currentBootcamps = [];

function buildStates(a, prevState, countedStates) {
    currentData = grads[a]
    let currentState = currentData[1];
    if(countedStates.includes(currentState) === false) {
        countedStates.push(currentState)
        data.children.push({name: currentState, children: []})
        
    }
    if(currentState === prevState) {
        currentBootcamps.push(currentData);
        prevBootcamp = currentData[0];
    } else {
        // console.log("prev boot camp ", prevBootcamp, "prev state ", countedStates.indexOf(prevState))
        console.log("current", a)
        let stateIndex = countedStates.indexOf(prevState);
        // let returnedArray = buildBootcamps(b, currentBootcamps, prevBootcamp, countedBootcamps);
        // console.log("before timeout", returnedArray, data.children[stateIndex].children)
        // data.children[stateIndex].children.push(...returnedArray);
        
        buildBootcamps(b, currentBootcamps, prevBootcamp, countedBootcamps).then((value) => {
            data.children[stateIndex].children.push(value);
            prevState = currentState;
            currentBootcamps = [];
            currentBootcamps.push(currentData);
        });
    }
    a++;
    // console.log(currentBootcamps)
    if (a < grads.length) {
        buildStates(a, prevState, countedStates)
    } else {
        console.log("finished")
    }
    // return data;
    
}
console.log(grads.length)
buildStates(a, prevState, countedStates)

// for (let a = 0; a<grads.length; a++) {

    // currentData = grads[a]
    // let currentState = currentData[1];
    // if(countedStates.includes(currentState) === false) {
    //     countedStates.push(currentState)
    //     data.children.push({name: currentState, children: []})
    // }
    // if(currentState === prevState) {
    //     currentBootcamps.push(currentData);
    // } else {
    //     buildBootcamps(currentBootcamps);
    //     prevState = currentState;
    // }
    
    
    
// }
//   console.log(countedStates)
//   let statesLength = data.children.length;
//   for (let i = 0; i < statesLength; i++) {
//       if (data.children[i].name === currentState) {
          
//       }
//       else {
//         data.children.push({name:grads[a][1], children:[]});
//       }
//   }
  
  
//   for (let b = 0; b<companies[a][0]; b++) {
    
//     let role = "";
//     let count = 0;  
//     let rndJob = Math.random()*100;    
//     for (let c = 0; c < roles.length; c++){  
      
//       if (count < rndJob) {
//         count += roles[c][1];
//       } else {
//         role = roles[c][0];
//         if (currentRoles.length == 0) {
//           currentRoles.push(role);
//           data.children[a].children.push({name:role, value: 1});
//         }else{
//           if (currentRoles.includes(role)){
//             data.children[a].children[currentRoles.indexOf(role)].value ++;
//           } else {
//             data.children[a].children.push({name:role, value: 1});
//             currentRoles.push(role);
//           }
//           break;
//         }
//       }
//     } 
//   }
// }
// console.log(data);
// console.log(data.children[4].children)