const newData = [["state"," company"," hires"],
["AL","Disability:IN","1"],
["AL","ShadowDragon","1"],
["AL","Giant Eagle","1"],
["AL","NextSite","1"],
["AL","Crossvale","2"],
["AL","Marshmello & Friends Co.","2"],
["AL","L&C Designs","2"],
["AL","Carrigans Public House","2"],
["AL","VIPKid","2"],
["AL","RxBenefits","2"],
["AL","Daxko","2"],
["AL","Target","2"],
["AL","FIS","3"],
["AL","Healthgrades","3"],
["CA","Airbnb","2"],
["CA","ServiceNow","2"],
["CA","HubSpot","3"],
["CA","CareerFoundry","3"],
["CA","Starbucks","3"],
["CA","Capital One","3"],
["CA","Thinkful","10"],
["CA","Self Employed","13"],
["CA","Google","13"],
["CA","Microsoft","14"],
["CA","Apple","15"],
["CA","Bit","1"],
["CA","VIKTOR","1"],
["CA","Citrix","1"],
["CA","Experian","1"],
["CA","Apogee Integration","1"],
["CA","Nucamp Coding Bootcamp","1"],
["CA","Webhelp","1"],
["CA","BCG Platinion","1"],
["CA","Abarca Health","1"],
["CA","Floyd County Productions","1"],
["CA","Philips","1"],
["CA","Answer Digital","1"],
["CA","Capital One","16"],
["CA","Uber","20"],
["CA","Microsoft","21"],
["CA","JPMorgan Chase & Co.","23"],
["CA","LinkedIn","25"],
["CA","Apple","26"],
["CA","Personal Projects","34"],
["CA","IBM","44"],
["CA","Amazon","45"],
["CA","Facebook","74"],
["CA","Personal Projects","77"],
["CA","Galvanize Inc","88"],
["CA","Google","92"],
["CA","Fastly","5"],
["CA","Dropbox","5"],
["CA","LinkedIn","5"],
["CA","Salesforce","6"],
["CA","Lyft","6"],
["CA","Bloomberg LP","6"],
["CA","PagerDuty","8"],
["CA","Slack","9"],
["CA","Apple","10"],
["CA","Datadog","11"],
["CA","Facebook","17"],
["CA","Google","25"],
["CA","Twilio Inc.","26"],
["CA","Target","27"],
["CA","Mercado Libre","4"],
["CA","Siigo S.A.","4"],
["CA","Taos","5"],
["CA","Avantica","5"],
["CA","Apple","5"],
["CA","Rappi","8"],
["CA","Altimetrik","8"],
["CA","Seguros Bolivar S.A","9"],
["CA","COMFAMA","10"],
["CA","Koombea","12"],
["CA","Globant","16"],
["CA","Novvum","3"],
["CA","VaynerCommerce","3"],
["CA","Blizzard Entertainment","3"],
["CA","Capital Group","3"],
["CA","Parcel Pending by Quadient","3"],
["CA","PriceSpider","3"],
["CA","Applied Medical","3"],
["CA","VoiceFoundry","4"],
["CA","Self-Employed","4"],
["CA","Member Splash","5"],
["CA","BeSmartee®","5"],
["CA","Codazen","7"],
["CA","Verys","7"],
["CA","Doctor Genius","7"],
["CA","Avance Venture Lab","2"],
["CA","MagmaLabs","2"],
["CA","NouKòd","3"],
["CA","Torre","3"],
["CA","Peoplebox","3"],
["CA","CareerFoundry","4"],
["CA","Upwork","14"],
["CA","Self Employed","17"],
["CA","Action Property Management","1"],
["CA","Sonoma State University","1"],
["CA","AUSAM","1"],
["CA","Lifehouse Agency","1"],
["CA","UFC","1"],
["CA","Mortgage Machine Services","1"],
["CA","Revature","1"],
["CA","Empower","1"],
["CA","Trilogy Education","1"],
["CA","Tabula Rasa HealthCare","1"],
["CA","LandMonk","2"],
["CA","Zigzy","2"],
["CA","RedApple Digital Health","2"],
["CA","TensorIoT Inc.","2"],
["CA","Accenture","1"],
["CA","Oracle","1"],
["CA","PlanetScale","1"],
["CA","YearOne (Techstars 2020)","2"],
["CA","Twilio Inc.","2"],
["CA","CleverCounsel LLC","2"],
["CA","Birst","2"],
["CA","Solvd","2"],
["CA","Workday","2"],
["CA","Dropbox","2"],
["CA","doc.ai","2"],
["CA","Pinterest","2"],
["CA","Dovenmuehle Mortgage","6"],
["CA","WePay","6"],
["CA","Bed Bath & Beyond","4"],
["CA","Hack for LA","6"],
["CA","Citi","8"],
["CA","IBM","8"],
["CA","Deloitte","10"],
["CA","Accenture","11"],
["CA","Wells Fargo","12"],
["CA","JPMorgan Chase & Co.","12"],
["CA","Google","13"],
["CA","Apple","20"],
["CA","Facebook","20"],
["CA","Amazon","31"],
["CA","stc","141"],
["CA","Aramco","146"],
["CA","Fiverr","150"],
["CA","Tata Consultancy Services","157"],
["CA","Infosys","174"],
["CA","Facebook","206"],
["CA","Accenture","208"],
["CA","IBM","221"],
["CA","Microsoft","306"],
["CA","Upwork","364"],
["CA","Amazon","368"],
["CA","Google","372"],
["co","Tech Mahindra","2"],
["co","Angi","2"],
["co","Booz Allen Hamilton","2"],
["co","The Walt Disney Company","2"],
["co","Bank of America","2"],
["co","Essendant","3"],
["co","Raytheon Intelligence & Space","3"],
["co","BIT Systems","3"],
["co","Charter Communications","3"],
["co","HomeAdvisor","3"],
["co","Ibotta","3"],
["co","CACI International Inc","4"],
["co","NexGen Technologies","6"],
["co","Comcast","6"],
["CO","Brandfolder","6"],
["CO","Peloton Interactive","6"],
["CO","Devetry (part of Dept)","7"],
["CO","Handshake","7"],
["CO","TaxJar","7"],
["CO","Fastly","8"],
["CO","Hotel Engine","9"],
["CO","Stitch Fix","10"],
["CO","Guild Education","14"],
["CO","Ibotta","16"],
["CO","Charter Communications","17"],
["CO","Allstate","17"],
["CO","Slalom","19"],
["CO","Aetna","21"],
["FL","Boosmap","2"],
["FL","Cornershop by Uber","2"],
["FL","Bridge Patient Portal","2"],
["FL","The Dog Company Chile","2"],
["FL","Patagonia IT","2"],
["FL","Nivelat","2"],
["FL","Bridges Unite","2"],
["FL","DNA HUMAN CAPITAL","3"],
["FL","Uber","3"],
["FL","University of Miami","3"],
["FL","Augusta Hitech","4"],
["FL","IntelePeer","5"],
["FL","Watsco Ventures","5"],
["FL","springbig","5"],
["FL","Miami Dev Shop","5"],
["FL","MDLIVE","5"],
["FL","Papa","5"],
["FL","Microsoft","5"],
["FL","Health Karma","6"],
["FL","Kipu Health","6"],
["FL","Apple","6"],
["FL","BrainStation","9"],
["FL","CareCloud","9"],
["FL","Restaurant Brands International","13"],
["GA","Microsoft","3"],
["GA","Luminare Inc.","4"],
["GA","Cox Automotive Inc.","4"],
["GA","Codoxo","4"],
["GA","Accenture","4"],
["GA","WarnerMedia","4"],
["GA","Mailchimp","5"],
["GA","Varsity Hype","5"],
["GA","Chick-fil-A Corporate Support Center","5"],
["GA","JPMorgan Chase & Co.","5"],
["GA","Umbrage","6"],
["GA","Ware2Go","6"],
["GA","Insiten","8"],
["GA","The Home Depot","12"],
["GA","XPO Logistics","1"],
["IL","Cartão de Todos","1"],
["IL","Codementor","1"],
["IL","Enova International","2"],
["IL","Grainger","2"],
["IL","Raise","2"],
["IL","Motorola Solutions","2"],
["IL","8th Light","2"],
["IL","Chicago Trading Company","3"],
["IL","US Navy","4"],
["IL","Army National Guard","4"],
["IL","United States Air Force","6"],
["IL","US Army","6"],
["IL","DRW","7"],
["IL","JPMorgan Chase & Co.","7"],
["IL","Birchwood Foods","1"],
["IL","Amazon","1"],
["IL","Capgemini","1"],
["IL","City Colleges of Chicago-Olive-Harvey College","1"],
["IL","Booz Allen Hamilton","1"],
["IL","U.S. Navy Reserve","1"],
["IL","Numerated","1"],
["IL","Beyond Finance","1"],
["IL","Copado","1"],
["IL","SORACOM Inc.","1"],
["IL","Datadog","1"],
["IL","Accenture","1"],
["IL","Convoy Inc","1"],
["IL","Upwork","2"],
["IN","Community Health Network","3"],
["IN","Navient","4"],
["IN","DMI (Digital Management","4"],
["IN","Ion Three","4"],
["IN","DoorDash","4"],
["IN","Agilify Automation","4"],
["IN","Liberty Mutual Insurance","4"],
["IN","US Army","4"],
["IN","Offprem Technology","6"],
["IN","TCC Software Solutions","6"],
["IN","R&M Software Inc.","7"],
["IN","Salesforce","7"],
["IN","GEICO","8"],
["IN","Infosys","12"],
["IN","Career Karma","2"],
["IN","SuperWorld","2"],
["IN","FedEx Ground","2"],
["IN","KellyConnect | Contact Center Solutions","2"],
["IN","Infosys","2"],
["IN","Zylo","2"],
["IN","JPMorgan Chase & Co.","2"],
["IN","AT&T","2"],
["IN","DMI (Digital Management","3"],
["IN","Amazon Logistics","4"],
["IN","Infosys Ltd","4"],
["IN","Southern New Hampshire University","8"],
["IN","Amazon Fulfillment Centre","16"],
["IN","Amazon","136"],
["MA","GlowByte Consulting","3"],
["MA","uTest","3"],
["MA","Sberbank","3"],
["MA","X5 Retail Group","3"],
["MA","Rostelecom","3"],
["MA","Infosys","3"],
["MA","JPMorgan Chase & Co.","3"],
["MA","OZON.ru","4"],
["MA","Sberbank","5"],
["MI","Spectrum Health","7"],
["MI","Perficient","7"],
["MI","Detroit Public Schools Community District","7"],
["MI","Meridian","8"],
["MI","MRM","8"],
["MI","Blue Cross Blue Shield of Michigan","11"],
["MI","United Shore","11"],
["MI","Detroit Labs","16"],
["MI","Ford Motor Company","16"],
["MI","Amrock","18"],
["MI","Accenture","20"],
["MI","Nexient","30"],
["MI","United Wholesale Mortgage","84"],
["MI","Quicken Loans","87"],
["MN","Slalom","7"],
["MN","Daugherty Business Solutions","7"],
["MN","U.S. Bank","8"],
["MN","Granicus","10"],
["MN","Total Expert","11"],
["MN","SPS Commerce","11"],
["MN","Accessible360","11"],
["MN","Datasite","12"],
["MN","Optum","13"],
["MN","Thomson Reuters","16"],
["MN","Travelers","19"],
["MN","C.H. Robinson","25"],
["MN","Best Buy","37"],
["MN","Target","37"],
["MO","Army National Guard","2"],
["MO","US Army","2"],
["MO","Revature","2"],
["MO","Washington University in St. Louis","3"],
["MO","LaunchCode","3"],
["MO","Best Buy","3"],
["MO","Slalom","3"],
["MO","Perficient","3"],
["MO","Self Employed","4"],
["MO","Mastercard","4"],
["MO","Accenture Federal Services","4"],
["MO","NISA Investment Advisors","5"],
["MO","GalaxE.Solutions","5"],
["MO","Charter Communications","6"],
["NC","Satellogic","1"],
["NC","Shelley Automation","1"],
["NC","Norges Bank Investment Management","1"],
["NC","","1"],
["NC","US Army","1"],
["NC","Milestone Digital","1"],
["NC","APEX Drone Racing","1"],
["NC","How-To Geek","1"],
["NC","Fitbit (now part of Google)","1"],
["NC","Bank of America","1"],
["NC","Verizon","1"],
["NC","JPMorgan Chase & Co.","1"],
["NC","Intel Corporation","1"],
["NC","Skytree | A Fresh Breath of Air","1"],
["NC","Zynga","2"],
["NJ","Incyte Studios","1"],
["NJ","PTC Therapeutics","1"],
["NJ","Robert Wood Johnson University Hospital","1"],
["NJ","Bizzabo","1"],
["NJ","Amazon","1"],
["NJ","Banfield Pet Hospital","1"],
["NY","New Relic","5"],
["NY","Etsy","7"],
["NY","Samsara","7"],
["NY","Twitter","8"],
["NY","DailyPay","8"],
["NY","Upwork","10"],
["NY","Zendesk","10"],
["NY","Uber","14"],
["NY","Medidata Solutions","18"],
["NY","Amazon","22"],
["NY","Bloomberg LP","37"],
["NY","Facebook","38"],
["NY","Wayfair","42"],
["NY","Google","86"],
["NY","Loblaw Digital","15"],
["NY","The University of British Columbia","19"],
["NY","Hootsuite","21"],
["NY","Rogers Sports & Media","22"],
["NY","BMO Financial Group","26"],
["NY","lululemon","33"],
["NY","Canadian Tire Corporation","33"],
["NY","TELUS","41"],
["NY","Konrad Group","45"],
["NY","TD","47"],
["NY","Scotiabank","49"],
["NY","CIBC","55"],
["NY","RBC","66"],
["NY","Shopify","80"],
["NY","Torus Teens","1"],
["NY","BACKED VC","1"],
["NY","Oracle","1"],
["NY","Tempus Labs","1"],
["NY","IBM","1"],
["NY","College Truckers","1"],
["NY","Self Improving","1"],
["NY","Capital Rx","1"],
["NY","Absa Group","2"],
["NY","Geodesic Techniques","2"],
["NY","NOV","3"],
["NY","JPMorgan Chase & Co.","5"],
["NY","SpryteLabs","8"],
["NY","Shopify","10"],
["NY","The New York Times","15"],
["NY","Spotify","16"],
["NY","Citi","21"],
["NY","Wayfair","23"],
["NY","WeWork","23"],
["NY","Accenture","27"],
["NY","Self Employed","28"],
["NY","IBM","31"],
["NY","Datadog","37"],
["NY","JPMorgan Chase & Co.","41"],
["NY","Amazon","44"],
["NY","Infosys","128"],
["NY","Wunderkind (Formerly BounceX)","8"],
["NY","BlackRock","9"],
["NY","Goldman Sachs","11"],
["NY","The New York Times","14"],
["NY","Northwestern Mutual","15"],
["NY","Spotify","16"],
["NY","Amazon","18"],
["NY","Etsy","20"],
["NY","American Express","25"],
["NY","JPMorgan Chase & Co.","26"],
["NY","Google","45"],
["NY","The Grace Hopper Program at Fullstack Academy","50"],
["NY","Bloomberg LP","67"],
["NY","Atlassian","62"],
["NY","Spotify","71"],
["NY","LinkedIn","78"],
["NY","Amazon Web Services (AWS)","94"],
["NY","Adobe","101"],
["NY","Salesforce","108"],
["NY","Accenture","134"],
["NY","IBM","149"],
["NY","Microsoft","151"],
["NY","Apple","152"],
["NY","Booz Allen Hamilton","181"],
["NY","Amazon","235"],
["NY","Facebook","243"],
["NY","Google","383"],
["NY","Uber","2"],
["NY","Comcast","2"],
["NY","City of Amsterdam","2"],
["NY","Warwick Investment Group","2"],
["NY","Disney Streaming Services","2"],
["NY","Citi","2"],
["NY","Bank of America","2"],
["NY","Tempus Labs","2"],
["NY","Trilogy Education","2"],
["NY","Google","3"],
["NY","IBM","3"],
["NY","The Spur Group","4"],
["NY","Amazon","4"],
["NY","Facebook","4"],
["NY","Conscience VC","2"],
["NY","Rodale Inc.","2"],
["NY","Penguin Random House","2"],
["NY","Meredith Corporation","2"],
["NY","The Conference Board","2"],
["NY","Pratt Institute","2"],
["NY","Verizon","2"],
["NY","JPMorgan Chase & Co.","2"],
["NY","Hachette Book Group","2"],
["NY","IBM","2"],
["NY","FCB Health","3"],
["NY","Upwork","3"],
["NY","Self-Employed","3"],
["NY","Scholastic","4"],
["NY","Apple","4"],
["NY","Finix","2"],
["NY","Anant","3"],
["NY","HubSpot","3"],
["NY","Hack for LA","3"],
["NY","Walmart Global Tech","3"],
["NY","Fiverr","4"],
["NY","Personal Projects","4"],
["NY","Upwork","7"],
["NY","IBM","8"],
["NY","Trilogy Education","10"],
["NY","Amazon","21"],
["OH","Shoptech Software - Manufacturing Software","1"],
["OH","Bottom Line Systems","1"],
["OH","Ohio National Financial Services","1"],
["OH","Eurostampa North America Inc.","1"],
["OH","Top Gun Sales Performance","1"],
["OH","Seven Hills Technology","1"],
["OH","The Cincinnati Insurance Companies","1"],
["OH","K-Electric","1"],
["OH","IBM","1"],
["OH","Matthews Automation Solutions","2"],
["OH","Great American Insurance Group","2"],
["OH","Total Quality Logistics","2"],
["OH","Procter & Gamble","3"],
["OH","Kroger Technology","4"],
["OH","Edaptive Computing","10"],
["OH","DICK'S Sporting Goods","11"],
["OH","AmTrust Financial Services","12"],
["OH","Fifth Third Bank","13"],
["OH","KeyBank","14"],
["OH","United Wholesale Mortgage","15"],
["OH","London Computer Systems","17"],
["OH","Nationwide","18"],
["OH","BNY Mellon","20"],
["OH","Olive","21"],
["OH","Progressive Insurance","34"],
["OH","National General Insurance","39"],
["OH","JPMorgan Chase & Co.","138"],
["OH","PNC","243"],
["OH","MoreSteam","3"],
["OH","CoverMyMeds","3"],
["OH","Apple","3"],
["OH","KeyBank","4"],
["OH","Foundation Software","4"],
["OH","Cardinal Health","4"],
["OH","Root Inc.","4"],
["OH","National General Insurance","5"],
["OH","Acumen Solutions","5"],
["OH","Nationwide","6"],
["OH","Huntington National Bank","6"],
["OH","PNC","9"],
["OH","Progressive Insurance","14"],
["OH","JPMorgan Chase & Co.","23"],
["OR","EventBuilder","1"],
["OR","Allocations","2"],
["OR","Esri","2"],
["OR","Hatch Data","2"],
["OR","Emsi","2"],
["OR","HealthSparq","2"],
["OR","Squishymedia","2"],
["OR","Kroger Technology","2"],
["OR","Schoolhouse","2"],
["OR","Kinship","3"],
["OR","Adobe","3"],
["OR","Nike","4"],
["OR","Sprinklr","5"],
["OR","Lithia Motors","5"],
["OR","PDXR","3"],
["OR","Hubb","3"],
["OR","Tuft & Needle","3"],
["OR","Pollinate","3"],
["OR","National Society of Black Engineers","3"],
["OR","Microsoft Leap Apprenticeship Program","3"],
["OR","iGrafx","4"],
["OR","Goalden Hour","4"],
["OR","UGrow","5"],
["OR","New Relic","6"],
["OR","Nike","6"],
["OR","Ascend Software","6"],
["OR","EyeCue Lab","7"],
["OR","Nombolo","8"],
["OR","The Home Depot","2"],
["OR","Adobe","2"],
["OR","Prosper-IT","2"],
["OR","Novus Labs","2"],
["OR","Smarsh","2"],
["OR","Epiq","2"],
["OR","Amazon","3"],
["OR","Conduent","3"],
["OR","Nike","4"],
["OR","Intel Corporation","4"],
["OR","Prosper I.T. Consulting","5"],
["OR","New Relic","5"],
["OR","Microsoft","6"],
["OR","Prosper IT Consulting","21"],
["TN","Tennessee Department of Transportation","9"],
["TN","naviHealth","9"],
["TN","National General Insurance","10"],
["TN","Aspire Health","10"],
["TN","Ncontracts","10"],
["TN","AllianceBernstein","11"],
["TN","Vanderbilt University Medical Center","12"],
["TN","FortyAU","12"],
["TN","Healthcare Bluebook","13"],
["TN","Ramsey Solutions","13"],
["TN","HealthStream","13"],
["TN","HCA Healthcare","16"],
["TN","Built Technologies","18"],
["TN","Accenture","38"],
["TX","Visio Lending","1"],
["TX","Digital Pharmacist Inc.","1"],
["TX","Siemens","1"],
["UT","TCN","6"],
["UT","Veryable","7"],
["UT","Workfront","7"],
["UT","projekt202","8"],
["UT","Vivint","14"],
["UT","Divvy | Inc.","14"],
["UT","Overstock.com","16"],
["UT","The Church of Jesus Christ of Latter-day Saints","17"],
["UT","Pluralsight","18"],
["UT","MX","22"],
["UT","Podium","25"],
["UT","The Church of Jesus Christ of Latter-day Saints","3"],
["UT","Mavenlink","3"],
["UT","ARUP Laboratories","3"],
["UT","Shareworks by Morgan Stanley","3"],
["UT","ExpertVoice","3"],
["UT","Direct®","3"],
["UT","Instructure","3"],
["UT","Goldman Sachs","3"],
["UT","Fidelity Investments","3"],
["UT","Divvy | Inc.","3"],
["UT","Nav Inc.","3"],
["UT","Acima Credit","4"],
["UT","MX","5"],
["UT","Verisys Corporation","6"],
["UT","Weave HQ","2"],
["UT","Impartner Software","2"],
["UT","IBM","2"],
["UT","Verisage Custom Software","3"],
["UT","XANT","3"],
["UT","VMware","3"],
["UT","Conscience VC","3"],
["UT","Fidelity Investments","3"],
["UT","O.C. Tanner","3"],
["UT","Smash Creative","4"],
["UT","Divvy | Inc.","4"],
["UT","Adobe","9"],
["WA","Abdul Aziz Al Ghurair School of Advanced Computing (ASAC)","6"],
["WA","Smartsheet","6"],
["WA","SAP Concur","7"],
["WA","F5","7"],
["WA","Nike","7"],
["WA","Slalom Build","8"],
["WA","US Army","9"],
["WA","Zonar Systems","10"],
["WA","Nordstrom","11"],
["WA","Expedia Group","13"],
["WA","Avalara","13"],
["WA","Amazon Web Services (AWS)","42"],
["WA","Amazon","48"],
["WA","Microsoft","100"],
["WA","The Difference Engine","5"],
["WA","Upwork","8"],
["WA","Mindtree","9"],
["WA","Conscience VC","10"],
["WA","Infosys","10"],
["WA","Google","11"],
["WA","US Army","12"],
["WA","Accenture","13"],
["WA","Amazon Web Services (AWS)","14"],
["WA","Self Employed","19"],
["WA","Amazon","52"],
["WA","Microsoft","53"],
["WA","Walgreens","3"],
["WA","Walmart","3"],
["WA","TEKsystems","3"],
["WA","Apple","3"],
["WA","United States Air Force","3"],
["WA","Infosys","3"],
["WA","US Army","3"],
["WA","Verizon","3"],
["WA","Amazon","8"],
["WA","Microsoft","9"],
["WA","Self Employed","10"]]